-- Supabase Database Schema for Content Automation System
-- Run this SQL in your Supabase SQL Editor to set up the database

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: content_sources
-- Stores information about web sources to scrape
CREATE TABLE IF NOT EXISTS content_sources (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    url TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    source_type TEXT NOT NULL, -- e.g., 'news', 'blog', 'social'
    scraping_frequency_minutes INTEGER DEFAULT 60,
    is_active BOOLEAN DEFAULT true,
    reliability_score FLOAT DEFAULT 1.0, -- 0.0 to 1.0
    last_scraped_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Table: scraped_content
-- Stores raw scraped data from web sources
CREATE TABLE IF NOT EXISTS scraped_content (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source_id UUID REFERENCES content_sources(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    title TEXT,
    content TEXT,
    summary TEXT,
    author TEXT,
    published_at TIMESTAMPTZ,
    scraped_at TIMESTAMPTZ DEFAULT NOW(),
    content_hash TEXT UNIQUE, -- For deduplication
    keywords TEXT[], -- Array of extracted keywords
    relevance_score FLOAT, -- 0.0 to 1.0, calculated by processing
    is_processed BOOLEAN DEFAULT false,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(url, content_hash)
);

-- Table: opus_jobs
-- Tracks all job executions sent to Opus
CREATE TABLE IF NOT EXISTS opus_jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_execution_id TEXT UNIQUE, -- From Opus API
    workflow_id TEXT NOT NULL,
    scraped_content_id UUID REFERENCES scraped_content(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'INITIATED', -- INITIATED, IN_PROGRESS, COMPLETED, FAILED
    job_payload JSONB, -- Input sent to Opus
    job_results JSONB, -- Output received from Opus
    error_message TEXT,
    retry_count INTEGER DEFAULT 0,
    initiated_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: generated_content
-- Stores content generated by Opus (before and after approval)
CREATE TABLE IF NOT EXISTS generated_content (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    opus_job_id UUID REFERENCES opus_jobs(id) ON DELETE CASCADE,
    scraped_content_id UUID REFERENCES scraped_content(id) ON DELETE SET NULL,
    content_type TEXT NOT NULL, -- 'industry_news', 'thought_leadership', etc.
    generated_text TEXT NOT NULL,
    target_platform TEXT DEFAULT 'twitter', -- 'twitter', 'linkedin', etc.
    is_approved BOOLEAN DEFAULT false,
    approved_by TEXT,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Table: published_posts
-- Stores information about posts published to social media
CREATE TABLE IF NOT EXISTS published_posts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    generated_content_id UUID REFERENCES generated_content(id) ON DELETE CASCADE,
    opus_job_id UUID REFERENCES opus_jobs(id) ON DELETE SET NULL,
    platform TEXT NOT NULL, -- 'twitter', 'linkedin', etc.
    post_id TEXT, -- Platform's post ID
    post_url TEXT,
    post_text TEXT NOT NULL,
    published_at TIMESTAMPTZ DEFAULT NOW(),
    engagement_metrics JSONB DEFAULT '{}'::jsonb, -- likes, retweets, etc.
    last_metrics_update TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Table: content_templates
-- Stores prompt templates for different content types
CREATE TABLE IF NOT EXISTS content_templates (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    content_type TEXT NOT NULL UNIQUE,
    template_name TEXT NOT NULL,
    system_prompt TEXT NOT NULL,
    user_prompt_template TEXT NOT NULL,
    temperature FLOAT DEFAULT 0.7,
    model_preference TEXT DEFAULT 'gpt-4',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Table: system_logs
-- General system logging and audit trail
CREATE TABLE IF NOT EXISTS system_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    log_level TEXT NOT NULL, -- INFO, WARNING, ERROR, etc.
    component TEXT NOT NULL, -- 'scraper', 'processor', 'opus_client', etc.
    message TEXT NOT NULL,
    context JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_scraped_content_source_id ON scraped_content(source_id);
CREATE INDEX IF NOT EXISTS idx_scraped_content_scraped_at ON scraped_content(scraped_at DESC);
CREATE INDEX IF NOT EXISTS idx_scraped_content_is_processed ON scraped_content(is_processed);
CREATE INDEX IF NOT EXISTS idx_scraped_content_relevance ON scraped_content(relevance_score DESC);
CREATE INDEX IF NOT EXISTS idx_opus_jobs_status ON opus_jobs(status);
CREATE INDEX IF NOT EXISTS idx_opus_jobs_job_execution_id ON opus_jobs(job_execution_id);
CREATE INDEX IF NOT EXISTS idx_generated_content_is_approved ON generated_content(is_approved);
CREATE INDEX IF NOT EXISTS idx_published_posts_platform ON published_posts(platform);
CREATE INDEX IF NOT EXISTS idx_published_posts_published_at ON published_posts(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_logs_created_at ON system_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_logs_component ON system_logs(component);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
CREATE TRIGGER update_content_sources_updated_at
    BEFORE UPDATE ON content_sources
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_opus_jobs_updated_at
    BEFORE UPDATE ON opus_jobs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_content_templates_updated_at
    BEFORE UPDATE ON content_templates
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Insert default content sources (examples)
INSERT INTO content_sources (url, name, source_type, scraping_frequency_minutes)
VALUES 
    ('https://techcrunch.com/category/artificial-intelligence/', 'TechCrunch AI', 'news', 60),
    ('https://www.theverge.com/ai-artificial-intelligence', 'The Verge AI', 'news', 60)
ON CONFLICT (url) DO NOTHING;

-- Insert default content templates
INSERT INTO content_templates (content_type, template_name, system_prompt, user_prompt_template, temperature)
VALUES 
    (
        'industry_news',
        'Industry News Tweet Generator',
        'You are a professional content strategist for an AI automation company called Opus. Your goal is to create engaging, informative tweets that showcase how AI automation is transforming industries. Be concise, insightful, and include a call-to-action when appropriate.',
        'Transform this industry news into an engaging tweet (max 280 characters):\n\nTitle: {title}\nSummary: {summary}\nURL: {url}\nKeywords: {keywords}\n\nCreate a tweet that:\n1. Highlights the key insight\n2. Relates it to business automation\n3. Encourages engagement\n4. Includes relevant hashtags',
        0.7
    ),
    (
        'thought_leadership',
        'Thought Leadership Tweet Generator',
        'You are a thought leader in AI and automation. Create insightful tweets that demonstrate deep understanding of automation trends and provide value to B2B decision makers.',
        'Create a thought-provoking tweet based on this insight:\n\n{summary}\n\nMake it:\n- Provocative but professional\n- Data-driven when possible\n- Relevant to business leaders\n- Under 280 characters',
        0.8
    ),
    (
        'case_study',
        'Case Study Tweet Generator',
        'You are a B2B marketing expert. Create compelling tweets that showcase real-world automation success stories and their business impact.',
        'Create a tweet highlighting this use case:\n\n{summary}\n\nFocus on:\n- Tangible business outcomes\n- ROI or efficiency gains\n- How Opus enables similar automation\n- Clear call-to-action\n\nMax 280 characters.',
        0.6
    )
ON CONFLICT (content_type) DO NOTHING;

-- Comments for documentation
COMMENT ON TABLE content_sources IS 'Web sources to scrape for content';
COMMENT ON TABLE scraped_content IS 'Raw scraped data from web sources';
COMMENT ON TABLE opus_jobs IS 'Opus workflow job execution tracking';
COMMENT ON TABLE generated_content IS 'AI-generated content from Opus workflows';
COMMENT ON TABLE published_posts IS 'Posts published to social media platforms';
COMMENT ON TABLE content_templates IS 'Prompt templates for content generation';
COMMENT ON TABLE system_logs IS 'System-wide logging and audit trail';
